os: osx
language: objective-c
env:
  matrix:
    - PYVERSION=python  PIP_CMD=pip  PYSMT_SOLVER="None"
    - PYVERSION=python  PIP_CMD=pip  PYSMT_SOLVER="msat"
    - PYVERSION=python  PIP_CMD=pip  PYSMT_SOLVER="z3"
#    - PYVERSION=python3 PIP_CMD=pip3 PYSMT_SOLVER="z3"

allow_failures:
  matrix:
      - PYVERSION=python  PIP_CMD=pip  PYSMT_SOLVER="msat"

install:
  - "brew update"
  - "brew install swig"
  - "brew install ${PYVERSION}"
  - hash -r ${PYVERSION}
  - "${PIP_CMD} install six"
  - "${PIP_CMD} install nose"
  - "${PIP_CMD} install urllib3"
  - "export BINDINGS_FOLDER=${HOME}/python_bindings/${PYSMT_SOLVER}"
  - "mkdir -p ${BINDINGS_FOLDER}"
  - "export PYTHON_EXE=`which ${PYVERSION}`"
  - "${PYTHON_EXE} install.py --confirm-agreement --bindings-path ${BINDINGS_FOLDER}"
  - "eval `${PYTHON_EXE} install.py --env --bindings-path ${BINDINGS_FOLDER}`"

script:
  - echo ${PYTHON_EXE}
  - "${PYTHON_EXE} --version"
  - "echo ${PYTHONPATH}"
  - "python install.py --check"
  - "nosetests pysmt -v"
